package exceptions;

public class MyException {
    public static void main(String[] args) {
        System.out.println("Inside MyException class");
    }
}
